### ISSUE TITLE
what's the exact url?

### ISSUE THREAD

**Issue by johndpope** [sheldygg/aiotiktok#3]
I try both of these 

https://www.tiktok.com/@sooshimango

https://www.tiktok.com/@sooshimango/video/7228919985777757442?lang=en

```
import asyncio
from aiotiktok import Client

tiktok = Client()

async def main():
    data = await tiktok.get_data(url="https://www.tiktok.com/@sooshimango/video/7228919985777757442?lang=en")
    print(data)
    
asyncio.run(main())

```

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    asyncio.run(main())
  File "/Users/johndpope/opt/miniconda3/envs/spleeter/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/johndpope/opt/miniconda3/envs/spleeter/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    data = await tiktok.get_data(url="https://www.tiktok.com/@sooshimango/video/7228919985777757442?lang=en")
  File "/Users/johndpope/Documents/gitWorkspace/aiotiktok/aiotiktok/client.py", line 82, in get_data
    video_id = await self.get_video_id(url)
  File "/Users/johndpope/Documents/gitWorkspace/aiotiktok/aiotiktok/client.py", line 34, in get_video_id
    if original_url == self.tiktok_url or "video" not in original_url:
UnboundLocalError: local variable 'original_url' referenced before assignment

**Comment by sheldygg** [comment]
sorry, that's my problem, already i fix it.
u can install new version 2.5.3 from PyPi

**Comment by johndpope** [comment]
thanks so much - this is working great.
