### ISSUE TITLE
405: Method Not Allowed

### ISSUE THREAD

**Issue by wweevv-johndpope** [sheldygg/aiotiktok#7]
signature_data: b'405: Method Not Allowed'
Traceback (most recent call last):
  File "/Users/johndpope/Desktop/test.py", line 11, in <module>
    asyncio.run(main())
  File "/Users/johndpope/miniconda3/envs/py310/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/johndpope/miniconda3/envs/py310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/johndpope/Desktop/test.py", line 8, in main
    await tiktok.user_feed_sig("playboicarti")
  File "/Users/johndpope/miniconda3/envs/py310/lib/python3.10/site-packages/aiotiktok/client.py", line 168, in user_feed_sig
    user_videos = (await self._get_user_feed_private(username))[:count]
  File "/Users/johndpope/miniconda3/envs/py310/lib/python3.10/site-packages/aiotiktok/client.py", line 136, in _get_user_feed_private
    "x-tt-params": signature_data.get("x-tt-params"),
AttributeError: 'bytes' object has no attribute 'get'

```
import asyncio
from aiotiktok import Client

tiktok = Client(signature_url="http://111.111.111.111:8002")
async def main():
    await tiktok.user_feed_sig("playboicarti")
asyncio.run(main())
```

I think it's a CORS issue - do I need SSL?

**Comment by wweevv-johndpope** [comment]
adding this didn't help

```
self.headers = {
            "Access-Control-Allow-Origin": "*.",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
        }
```

**Comment by wweevv-johndpope** [comment]
my bad add signature resolved it
 tiktok = Client(signature_url="http://111.111.111.111:8002/signature")
